version: 3

vars:
  ReleaseName: "code-server"
  ReleaseNamespace: "code-server"

tasks:
  install:
    cmds:
      - helm upgrade --install {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace . -f .secrets/values.yml

  template:
    cmds:
      - helm template --dry-run {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace . -f .secrets/values.yml

  uninstall:
    cmds:
      - helm uninstall {{.ReleaseName}} -n {{.ReleaseNamespace}}
