apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      mongodb: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        mongodb: mongodb
    spec:
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb
      containers:
      - name: mongodb
        image: mongo:4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
