version: 3

vars:
  ReleaseName: "qdrant"
  ReleaseNamespace: "testing-qdrant"

tasks:
  install:
    cmds:
      - helm upgrade --install {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace .

  template:
    cmds:
      - helm template --dry-run {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace . --debug

  uninstall:
    cmds:
      - helm uninstall {{.ReleaseName}} -n {{.ReleaseNamespace}}
