apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: openwebui
spec:
  volumeClaimTemplates:
  - metadata:
      name: openwebui-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  selector:
    matchLabels:
      app: openwebui
  replicas: 1
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
      - name: app
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: openwebui-data
          mountPath: /app/backend/data