apiVersion: v2
name: vscode
description: A Helm chart for Kubernetes to run vscode
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: library
  version: 0.1.0
  repository: file://../_library/
