codeServer:
  storage: 
    size: "5Gi"
    className: ""

  nodeSelector: {}
  tolerations: []

  extensions:
    - ms-python.python
    - golang.Go

  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "1000Mi"

  ingress:
    enabled: false
    className: ""

    host: ""
    clusterIssuer: ""

mongodb:
  storage:
    size: "1Gi"
    # className: ""

  nodeSelector: {}
  tolerations: []

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
