replicaCount: 1

image:
  repository: jenkins/jenkins
  tag: "lts"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "1000m"
    memory: "1024Mi"
  limits:
    cpu: "2000m"
    memory: "2048Mi"


ingress:
  enabled: true
  host: "jenkins.example.com"
  className: nginx
  clusterIssuer: "kloudlite-cert-issuer"
  cors:
    enabled: false
    origins: []

admin:
  user: admin
  password: admin123

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

