controller:
  admin:
    username: "admin"
    password: "admin123"
  serviceType: NodePort

persistence:
  enabled: false

ingress:
  enabled: false
  className: ""
  clusterIssuer: ""

host: ""
cors:
 enabled: false
 origins: []
