apiVersion: v2
name: mariadb
description: MariaDB is an open source, community-developed SQL database server that
  is widely in use around the world due to its enterprise features, flexibility, and
  collaboration with leading tech firms.
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: mariadb
  version: 20.2.2
  repository: "https://charts.bitnami.com/bitnami"
