mariadb:
  architecture: standalone
  primary:
    nodeSelector: {}
    tolerations: []
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"

  secondary:
    replicaCount: 0

  expose:
    host: ""
