apiVersion: v2
appVersion: 1.4.1

dependencies:
- name: flux
  version: 2.4.3
  repository: "oci://registry-1.docker.io/bitnamicharts"

description: Source Controller is a component of Flux. Flux is a tool for keeping
  Kubernetes clusters in sync with sources of configuration.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
- deployment
- gitops
- cd
- continuous-delivery
- helm
- kustomize
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mh-flux
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/flux
version: 2.4.3