apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.name" . }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    mongodb: {{ include "mongodb.name" . }}
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
