ingress:
  enabled: true
  className: apache
  host: apache.machinehack-new.clients.kloudlite.io
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"
  service:
    type: ClusterIP
    port: 80
