deploymentMode: SimpleScalable  # Use 'SingleBinary' for monolithic mode

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

# Enable MinIO for object storage
minio:
  enabled: true
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  persistence:
    enabled: true
    size: 10Gi  # Adjust based on log storage requirements

# External exposure using Ingress
ingress:
  enabled: true
  className: "nginx"
  hostSuffix: "machinehack-new.clients.kloudlite.io"
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"

    
# Configure Service type for external access
service:
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
  ports:
    http: 3100
    grpc: 9095

# Resource limits for smooth operation
resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

# Zero out unnecessary components when using SimpleScalable mode
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Pod Security Context to ensure Loki runs with the correct permissions
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000
