apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-exports"
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  CODE_SERVER_PASSWORD: '{{ include "variables.code-server-password" . }}'
  CODE_SERVER_URL: "https://{{.Values.codeServer.ingress.host}}"
