image:
  repository: n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  annotations: 
    cert-manager.io/cluster-issuer: kloudlite-cert-issuer
  hosts:
    - host: n8n.machinehack-new.clients.kloudlite.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"
replicaCount: 1
resources: {}
  
env:
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "password"

nodeSelector: {}
tolerations: []
affinity: {}
