name: Update Template Listing

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_run:
    workflows: ["Release Helm Charts"]
    types:
      - completed

  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    runs-on: ubuntu-latest
    # runs-on: blacksmith-4vcpu-ubuntu-2204
    if: ${{ github.event_name  == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: kubectl
        uses: nxtcoder17/actions/setup-kubectl@main

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Installing yq (with pip)
        run: |+
          pip install yq

      - name: setup kubeconfig file
        run: |+
          cat > /tmp/kubeconfig <<EOF
          $(echo "${{ secrets.HA_CLUSTER_KUBE_CONFIG }}" | base64 -d)
          EOF

          echo "KUBECONFIG=/tmp/kubeconfig" | tee -a $GITHUB_ENV

      - name: Update API env templates
        run: |+
          repo_full=${{ github.repository }}
          repo_name=${repo_full#*/}
          curl -L0 https://${{ github.repository_owner }}.github.io/$repo_name/env-template.yml | yq '[.[] | select(.name | startswith( "_") | not )]' -y -c > template.yml 

          cat > config.yml <<EOF
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: api-v2-config
            namespace: kloudlite
            annotations:
              kloudlite.io/updated.by: "github-workflow"
              kloudlite.io/updated.at: "$(date --rfc-2822)"
          data:
            env-template.yml: |+
          $(sed 's/^/    /' template.yml)
          EOF

          kubectl apply -f config.yml

          kubectl rollout restart deployment/api-v2 -n kloudlite
